### ISSUE TITLE
empty etcd hosts

### ISSUE THREAD

**Issue by forging2012** [suyuan32/simple-admin-core#188]
**Describe the bug**

### empty etcd hosts

simple-admin-core/api
➜  api git:(dev) ✗ go run core.go -f etc/core_dev.yaml          

string(jsonConf):  {"Name":"core.api","Log":{"ServiceName":"coreApiLogger","Mode":"file","Encoding":"json","TimeFormat":"","Path":"logs/api","Level":"info","MaxContentLength":0,"Compress":false,"Stat":true,"KeepDays":7,"StackCoolDownMillis":100,"MaxBackups":0,"MaxSize":0,"Rotation":"daily"},"Mode":"pro","MetricsUrl":"","Prometheus":{"Host":"","Port":0,"Path":""},"Telemetry":{"Name":"","Endpoint":"","Sampler":0,"Batcher":"","OtlpHeaders":null,"OtlpHttpPath":"","Disabled":false},"DevServer":{"Enabled":false,"Host":"","Port":0,"MetricsPath":"","HealthPath":"","EnableMetrics":false,"EnablePprof":false},"Host":"127.0.0.1","Port":9100,"CertFile":"","KeyFile":"","Verbose":false,"MaxConns":10000,"MaxBytes":1048576,"Timeout":30000,"CpuThreshold":900,"Signature":{"Strict":false,"Expiry":0,"PrivateKeys":null},"Middlewares":{"Trace":true,"Log":true,"Prometheus":true,"MaxConns":true,"Breaker":true,"Shedding":true,"Timeout":true,"Recover":true,"Metrics":true,"MaxBytes":true,"Gunzip":true},"TraceIgnorePaths":null,"Auth":{"AccessSecret":"jS6VKDtsJf3z1n2VKDtsJf3z1n2","AccessExpire":259200},"RedisConf":{"Host":"127.0.0.1:6379","Type":"node","Pass":"","Tls":false,"NonBlock":true,"PingTimeout":1000000000},"CoreRpc":{"Etcd":{"Hosts":["127.0.0.1:2379"],"Key":"core.rpc","ID":0,"User":"","Pass":"","CertFile":"","CertKeyFile":"","CACertFile":"","InsecureSkipVerify":false},"Endpoints":null,"Target":"","App":"","Token":"","NonBlock":false,"Timeout":2000,"KeepaliveTime":0,"Enabled":true,"Middlewares":{"Trace":true,"Duration":true,"Prometheus":true,"Breaker":true,"Timeout":true}},"JobRpc":{"Etcd":{"Hosts":null,"Key":"","ID":0,"User":"","Pass":"","CertFile":"","CertKeyFile":"","CACertFile":"","InsecureSkipVerify":false},"Endpoints":null,"Target":"","App":"","Token":"","NonBlock":false,"Timeout":2000,"KeepaliveTime":0,"Enabled":true,"Middlewares":{"Trace":true,"Duration":true,"Prometheus":true,"Breaker":true,"Timeout":true}},"McmsRpc":{"Etcd":{"Hosts":null,"Key":"","ID":0,"User":"","Pass":"","CertFile":"","CertKeyFile":"","CACertFile":"","InsecureSkipVerify":false},"Endpoints":null,"Target":"","App":"","Token":"","NonBlock":false,"Timeout":2000,"KeepaliveTime":0,"Enabled":true,"Middlewares":{"Trace":true,"Duration":true,"Prometheus":true,"Breaker":true,"Timeout":true}},"Captcha":{"KeyLong":5,"ImgWidth":240,"ImgHeight":80,"Driver":"\"digit\""},"DatabaseConf":{"Host":"127.0.0.1","Port":3306,"Username":"root","Password":"root","DBName":"simple_admin","SSLMode":"disable","Type":"mysql","MaxOpenConn":100,"CacheTime":10,"DBPath":"","MysqlConfig":"","PGConfig":"","SqliteConfig":""},"CasbinConf":{"ModelText":"[request_definition]\nr = sub, obj, act\n[policy_definition]\np = sub, obj, act\n[role_definition]\ng = _, _\n[policy_effect]\ne = some(where (p.eft == allow))\n[matchers]\nm = r.sub == p.sub \u0026\u0026 keyMatch2(r.obj,p.obj) \u0026\u0026 r.act == p.act\n"},"I18nConf":{"Dir":""},"ProjectConf":{"DefaultRoleId":1,"DefaultDepartmentId":1,"DefaultPositionId":1,"EmailCaptchaExpiredTime":600,"SmsTemplateId":"","SmsAppId":"","SmsSignName":"","RegisterVerify":"captcha","LoginVerify":"captcha","ResetVerify":"email"},"CROSConf":{"Address":"*"}}
2023/09/10 15:30:20 empty etcd hosts

这里报错了“ empty etcd hosts”

goroutine 1 [running]:
runtime/debug.Stack()
	/Users/admin/.go/current/src/runtime/debug/stack.go:24 +0x65
github.com/zeromicro/go-zero/core/logx.Must({0x102e39340?, 0xc000c86650?})
	/Users/admin/go/pkg/mod/github.com/suyuan32/simple-admin-tools@v1.5.16/core/logx/logs.go:225 +0x57
github.com/zeromicro/go-zero/zrpc.NewClientIfEnable({{{0x0, 0x0, 0x0}, {0x0, 0x0}, 0x0, {0x0, 0x0}, {0x0, 0x0}, ...}, ...}, ...)
	/Users/admin/go/pkg/mod/github.com/suyuan32/simple-admin-tools@v1.5.16/zrpc/client.go:57 +0x85
github.com/suyuan32/simple-admin-core/api/internal/svc.NewServiceContext({{{{0xc000427708, 0x8}, {{...}, {...}, {...}, {...}, {...}, {...}, 0x0, 0x0, ...}, ...}, ...}, ...})
	/Users/admin/Workspace/Development/go/go-zero/simple-admin/simple-admin-core/api/internal/svc/service_context.go:51 +0x29f
main.main()
	/Users/admin/Workspace/Development/go/go-zero/simple-admin/simple-admin-core/api/core.go:53 +0x290
exit status 1
➜  api git:(dev) ✗ 

ETCD中有core.rpc的注册信息
<img width="646" alt="image" src="https://github.com/suyuan32/simple-admin-core/assets/6813552/f27477eb-7803-460b-ba6c-fb4df4178db8">

➜  api git:(dev) ✗ go version
go version go1.20.8 darwin/amd64

**api/etc/core_dev.yaml 配置如下：**

```
Name: core.api
Host: 127.0.0.1
Port: 9100
Timeout: 30000

Etcd:
  Hosts:
    - 127.0.0.1:2379
  Key: api

CoreRpc:
  Etcd:
    Hosts:
      - 127.0.0.1:2379
    Key: core.rpc
    Enabled: true

Auth:
  AccessSecret: jS6VKDtsJf3z1n2VKDtsJf3z1n2 # JWT的加密密钥，各个API应保持一致才能解析
  AccessExpire: 259200 # 秒，过期时间

Log:
  ServiceName: coreApiLogger
  Mode: file
  Path: logs/api # log 保存路径，使用filebeat同步
  Level: info
  Compress: false
  KeepDays: 7 # 保存时长（天）
  StackCoolDownMillis: 100

RedisConf:
  Host: 127.0.0.1:6379 # 改成自己的redis地址
  Type: node
  # Pass: xxx  # 也可以设置密码


Captcha:
  KeyLong: 5 # 验证码长度
  ImgWidth: 240 # 验证码图片宽度
  ImgHeight: 80 # 验证码图片高度
  Driver: digit # 支持三种驱动 digit, string, math, 默认为 digit

DatabaseConf:
  Type: mysql # 支持 mysql, postgres, sqlite3
  Host: "127.0.0.1" # 修改成自己的mysql地址
  Port: 3306
  DBName: simple_admin # 数据库名称
  Username: root # 用户名
  Password: "root" # 密码
  MaxOpenConn: 100 # 最大连接数
  SSLMode: disable # 是否在 postgresql 中使用 SSL, disable 或 require
# DBPath: /home/data/sqlite.db # Sqlite 数据库文件存放位置，使用 sqlite3时必须设置
# MysqlConfig: '&charset=utf8&loc=Asia/Shanghai' # Mysql的额外配置
# PGConfig: ''  # Postgresql 的额外配置
# SqliteConfig: '' # Sqlite 的额外配置

# casbin 规则
CasbinConf:
  ModelText: |
    [request_definition]
    r = sub, obj, act
    [policy_definition]
    p = sub, obj, act
    [role_definition]
    g = _, _
    [policy_effect]
    e = some(where (p.eft == allow))
    [matchers]
    m = r.sub == p.sub && keyMatch2(r.obj,p.obj) && r.act == p.act

I18nConf:
  Dir: # I18n 文件的外部路径，若不为空则会读取外部，若为空则读取二进制文件内部的i18n文件

CROSConf:
  Address: '*'    # if it is *, allow all ip and address. e.g. http://example.com

ProjectConf:
  DefaultRole: 1 # 注册用户默认的角色ID
  DefaultDepartment: 1 # 注册用户默认的部门 ID
  DefaultPosition: 1 # 注册用户默认的职位 ID
```

**rpc/etc/core_dev.yaml**
配置如下：

```
Name: core.rpc
ListenOn: 127.0.0.1:9101

Etcd:
  Hosts:
    - 127.0.0.1:2379
  Key: core.rpc

CoreRpc:
  Etcd:
    Hosts:
      - 127.0.0.1:2379
    Key: core.rpc

#CoreRpc:
#  Endpoints:
#    - 127.0.0.1:9101 # 与 Core RPC 地址相同
#  Enabled: true # 是否启用

DatabaseConf:
  Type: mysql # 支持 mysql, postgres, sqlite3
  Host: "127.0.0.1" # 修改成自己的mysql地址
  Port: 3306
  DBName: simple_admin # 数据库名称
  Username: root # 用户名
  Password: "root" # 密码
  MaxOpenConn: 100 # 最大连接数
  SSLMode: disable # 是否在 postgresql 中使用 SSL, disable 或 require
# DBPath: /home/data/sqlite.db # Sqlite 数据库文件存放位置，使用 sqlite3时必须设置
# MysqlConfig: '&charset=utf8&loc=Asia/Shanghai' # Mysql的额外配置
# PGConfig: ''  # Postgresql 的额外配置
# SqliteConfig: '' # Sqlite 的额外配置

# casbin 规则
CasbinConf:
  ModelText: |
    [request_definition]
    r = sub, obj, act
    [policy_definition]
    p = sub, obj, act
    [role_definition]
    g = _, _
    [policy_effect]
    e = some(where (p.eft == allow))
    [matchers]
    m = r.sub == p.sub && keyMatch2(r.obj,p.obj) && r.act == p.act

Log:
  ServiceName: coreRpcLogger
  Mode: file
  Path: logs/rpc # log 保存路径，使用filebeat同步
  Encoding: json
  Level: info
  Compress: false
  KeepDays: 7 # 保存时长（天）
  StackCoolDownMillis: 100

RedisConf:
  Host: 127.0.0.1:6379 # 改成自己的redis地址
  Type: node
  # Pass: xxx  # 也可以设置密码
```
