### ISSUE TITLE
swagger response type definition wrong

### ISSUE THREAD

**Issue by waltcow** [suyuan32/simple-admin-core#27]
<img width="1221" alt="image" src="https://user-images.githubusercontent.com/3941174/197681991-cbe1c073-3bf9-42d7-941a-c3a5a15b99fa.png">

**Comment by suyuan32** [comment]
Please tell me more details.

**Comment by suyuan32** [comment]
![image](https://user-images.githubusercontent.com/21239039/197685462-9dfedaf8-9ac2-45d8-a537-6c8d5fa53a17.png)
Which type is wrong?

**Comment by waltcow** [comment]
in `GetUserInfoResp` 
```
        headers:
            UUID:
                description: User's UUID | 用户的UUID
                type: string
            avatar:
                description: The user's avatar path | 用户的头像路径
                type: string
            nickname:
                description: user's nickname | 用户的昵称
                type: string
            username:
                description: User name | 用户名
                type: string
```

all above fields should be nested in `$ref: '#/responses/GetUserInfoResp'`
